version: '3.8'

services:
  development-team:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: campfire-development-team
    ports:
      - "8080:8080"
    environment:
      - CAMPFIRE_VALLEY_ENV=docker
      - CAMPFIRE_VALLEY_HOST=0.0.0.0
      - CAMPFIRE_VALLEY_PORT=8080
      - PYTHONPATH=/app
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./config:/app/config:ro
      - ./logs:/app/logs
      - ./data:/app/data
      - ./reports:/app/reports
      - development_team_data:/app/persistent_data
    networks:
      - campfire-network
    depends_on:
      - redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Optional: Redis for caching and session management
  redis:
    image: redis:7-alpine
    container_name: campfire-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - campfire-network
    restart: unless-stopped
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Optional: Monitoring with Prometheus metrics
  prometheus:
    image: prom/prometheus:latest
    container_name: campfire-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    networks:
      - campfire-network
    restart: unless-stopped
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'

volumes:
  development_team_data:
    driver: local
  redis_data:
    driver: local
  prometheus_data:
    driver: local

networks:
  campfire-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16